import logging
import json
import os
from agentic_launchpad.modules.upsell_agent import generate_upsell_payload
from agentic_launchpad.modules.email_campaign.thank_you_agent import send_thank_you_email