import sys, os, subprocess, threading, time, traceback, shutil, requests
from realms_dispatch_unified import dispatch_to_platform
from dotenv import load_dotenv
from datetime import datetime
from pathlib import Path
from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse
import stripe
from realms_agentic_core.lead_harvest_agent import harvest_leads
from realms_agentic_core.email_validation_agent import validate_email_list
from superimage.content_creator import ContentCreator
from agentic_launchpad.modules.stripe_checkout_agent import inject_stripe_cta
from agentic_launchpad.make_payload_builder import build_payload
from agentic_launchpad.modules.email_campaign.email_dispatch_agent import dispatch_email_campaign
from agentic_launchpad.modules.syndication_agent import syndicate_to_channels
from realms_agentic_core.make_dispatch_trigger import trigger_make_scenario
from realms_agentic_core.dispatch_healer_agent import heal_dispatch_failures
from agentic_launchpad.system_healer import heal_system_if_needed
from realms_agentic_core.monetization.generate_revenue_chart import estimate_revenue
from agentic_launchpad.audit.fallback_manager import assign_fallback_agent
from agentic_launchpad.patch_and_repair import execute_repair
from agentic_launchpad.modules.email_campaign.thank_you_agent import send_thank_you_email
from agentic_launchpad.modules.upsell_agent import generate_upsell_payload
from realms_agentic_core.diagnostics.reflex_dispatcher import diagnose_failure