on:
  schedule:
    - cron: '0 6 * * *'
    - cron: '0 10 * * *'
    - cron: '0 14 * * *'
    - cron: '0 18 * * *'
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  syndicate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Syndication Master
        run: python agentic_launchpad/syndication_master.py